### PR TITLE
Add more pre-commit checks

### PR DESCRIPTION
**Pull request by AetherUnbound**
This PR adds `isort` to the list of checks to be run in pre-commit

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Something is seriously screwy with my local env 😭 this passed for me!!!

**Comment by sarayourfriend** [comment]
@AetherUnbound I think black and isort are fighting each other:

```
# pre-commit run --all-files
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
Check that executables have shebangs.....................................Passed
Check JSON...........................................(no files to check)Skipped
Check for case conflicts.................................................Passed
Check Toml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check Xml............................................(no files to check)Skipped
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Mixed line ending........................................................Passed
Pretty format JSON...................................(no files to check)Skipped
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /Users/sara/projects/parler-data-searcher/src/app.py
Fixing /Users/sara/projects/parler-data-searcher/src/templatefilters.py

flake8...................................................................Passed
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted src/templatefilters.py
reformatted src/app.py
All done! ✨ 🍰 ✨
2 files reformatted, 10 files left unchanged.

mypy.....................................................................Passed

# git status
On branch feature/isort
Your branch is up to date with 'origin/feature/isort'.

nothing to commit, working tree clean
```

**Comment by AetherUnbound** [comment]
Oh that's gotta be it, there's a way to fix this (I have in another repo) I just need to find it

**Comment by sarayourfriend** [comment]
Here's a blog post about it: https://copdips.com/2020/04/making-isort-compatible-with-black.html

**Comment by AetherUnbound** [comment]
Updated with a bunch more goodies too!

**Review by sarayourfriend — APPROVED** [review]

**Pull request merged**
